"""Added name column to links table

Revision ID: c001e1213b52
Revises: 6b317a700a03
Create Date: 2023-12-18 17:23:43.473093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c001e1213b52'
down_revision = '6b317a700a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=2000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_links', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
