services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=saias122
      - MYSQL_DATABASE=osradar
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  flask-app:
    container_name: flask-app
    build: app
    restart: always
    ports:
      - "80:80"
    networks:
      - backend

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask-app
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
