services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=saias122
      - MYSQL_DATABASE=osradar
    ports:
      - "3308:3306"
    volumes:
      # - ./mysql_dumps:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  flask-app:
    container_name: flask-app
    build: app
    restart: always
    volumes:
      - ./app:/usr/src/app
    networks:
      - backend
    depends_on:
      - mysql-db

  react-frontend:
    container_name: react-frontend
    build:
      context: ./test-frontend
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - flask-app

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" # Map to 443 instead if using SSL
    depends_on:
      - flask-app
      - react-frontend
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data:
