services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=saias122
      - MYSQL_DATABASE=osradar
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_dumps:/docker-entrypoint-initdb.d
    networks:
      - backend

  flask-app:
    container_name: flask-app
    build: app
    restart: always
    volumes: # Add this line
      - ./app:/usr/src/app # Mount the app directory
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - mysql-db

  react-frontend:
    container_name: react-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes: # Add this line
      - ./frontend:/usr/src/frontend # Mount the frontend directory
    networks:
      - backend
    depends_on:
      - flask-app

networks:
  backend:
